### ISSUE TITLE
Chart not mobile-friendly

### ISSUE THREAD

**Issue by benhammondmusic** [dmossakowski/additive-spotify-analyzer#18]
This was really fun to explore how my kids have taken over my Spotify list lol. However, the formatting is difficult on mobile (at least Brave on iPhone XR). The chart is larger than the display, but pinch to zoom out doesn't work because of the cropping/zooming functionally built into the chart. ![image](https://user-images.githubusercontent.com/41567007/109452340-c5b37200-7a0c-11eb-8f3a-0664f03c8827.png)

**Comment by dmossakowski** [comment]
Thanks for checking it out. Yeah the charts are not very mobile friendly. I just pushed an update that removes the hardcoded width but it just doesn't look very good all squished in.
![image](https://user-images.githubusercontent.com/711178/109713058-0ba13f00-7ba1-11eb-9815-e5a84d752301.png)

**Comment by dmossakowski** [comment]
There are no plans to make this website fully phone friendly so I will close this issue.

**Comment by benhammondmusic** [comment]
Sounds good! Also, this is my ever time making an issue as I'm pretty new. Should I have closed this issue myself once you'd mentioned in your last reply that it wasn't going to really work this way on mobile? I'm just not sure best practices going forward for opening and closing issues etc. thanks again for a cool project!
